name: CI/CD - Build, Push Docker & Deploy to ACI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/taxprep-demo:latest

  deploy-to-aci:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.ACI_RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.ACI_DNS_LABEL }}
          image: ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/taxprep-demo:latest
          name: taxprep-demo
